### ISSUE TITLE
Generators: Utility intents for all templates should be using training data from prebuilt models

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-components#1014]
## Describe the bug

Utility intents for all templates should be using training data from the prebuilt domains rather than those selected by a developer ;-)  Whilst we only support english today we will quickly have to add further languages which the prebuilts support. This will ensure a higher quality LU experience.

https://github.com/microsoft/luis-prebuilt-domains/tree/master/PrebuiltModels/Utilities

Going out without these at Build will result in projects with poor (?) quality LU intents for utility intents which won't be updated as we evolve templates in the future.

## Version

2.0.0-nightly.239644

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by lauren-mills** [comment]
@ryanlengel - let's talk about this. If we use the full dataset from the prebuilt domain, it could have negative impacts on our overall training

**Comment by ryanlengel** [comment]
> @ryanlengel - let's talk about this. If we use the full dataset from the prebuilt domain, it could have negative impacts on our overall training

Agreed, we started off with using the full dataset for intents and were advised to scale them back. We can revisit this.

**Comment by lauren-mills** [comment]
I looked at the latest version of the utilities pre-built model, and the cancel intent has 32 training utterances. This is quite a lot for the root bot and means we could easily trigger interruptions etc. when in skill conversations because of so many variations for cancel. We want to make it a pretty specific and narrow criteria for triggering to reduce false positives.

I think we should provide this feedback to the LUIS team to make sure the Utilities model doesn't overpower other models included with it in Assistants, but I do no think we should take this for R13 as it could compromise our currently tested experiences.

**Comment by sgellock** [comment]
Shiproom - moved out of R13 to R14

**Comment by lauren-mills** [comment]
Changed to P1 since it does not block this release.
