### ISSUE TITLE
Teams.SendMessageToTeamsChannel is not supported by the current adapter.

### ISSUE THREAD

**Issue by Bolleman** [microsoft/botframework-components#1150]
## Describe the bug

Using the "Send a message to a teams channel" action returns the error:  Teams.SendMessageToTeamsChannel is not supported by the current adapter.

## Version

Microsoft.Bot.Components.Teams 1.0.0
Composer:
Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

Add "Send a message to a teams channel" action in Composer and configure per screenshot below.

## Expected behavior

No error

## Screenshots

![send message to teams channel](https://user-images.githubusercontent.com/8999611/121760215-5dc9f880-cade-11eb-899b-383a3143bab5.png)

**Comment by EricDahlvang** [comment]
Hi @Bolleman 

Thank you for raising this issue.  We are in the process of integrating libraries and samples with new CloudAdapter. Unfortunately, this call is not supported yet, but will be in the next release with this update: https://github.com/microsoft/botbuilder-dotnet/pull/5562 

This can now be modified to work with CloudAdapter: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs#L233

Finally, this check will be removed: https://github.com/microsoft/botframework-components/blob/main/packages/Teams/dotnet/Actions/SendMessageToTeamsChannel.cs#L121

**Comment by stevengum** [comment]
@Bolleman, as @EricDahlvang indicated, this bug has been fixed in `main` of botbuilder-dotnet and will be going out in the 4.14.x release of the Bot Framework SDK for .NET. (https://github.com/microsoft/botbuilder-dotnet/pull/5728)

In the meantime, please use the workarounds provided by Eric in his comment above: https://github.com/microsoft/botframework-components/issues/1150#issuecomment-862581370

Closing this issue as the fix is ready to go live in the 4.14.x release and a workaround has been provided.
