### ISSUE TITLE
Composer 2.0 not configuring QnA Maker properly when using the Enterprise Assistant Bot Template

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/botframework-components#1185]
## Describe the bug

Reported from customer:

_Composer 2.0 does not properly configure QnA Maker when I using the enterprise assistant bot template.  I had it create the QnA Maker KB during the Getting Started steps which did successfully create the QnA Maker KB and properly configure the subscriptionKey, endpointKey, and qnaRegion but not knowledgebaseid or hostname… they both had not value set and I had to drop into Advance settings and set them manually and they things worked fine.  I am assuming that the expected behavior should be that they should be getting set, correct?  Just seems strange that it can provision the KB and set the subscriptionKey and endpointKey correctly but can’t seem to set the other two settings.  Any ideas what might be going on here?_

**Comment by lauren-mills** [comment]
Seems like this is referring to the settings need to use the QnA Maker action, rather than the settings needed to use the QnA recognizer connected to a dialog. 

Composer's built-in provisioning and publishing support for QnA Maker do not update appsettings with these keys. Our preferred approach to including knowledge bases is through the recognizer mechanism tied to a dialog (the ChitchatDialog is a good example). This enables Composer to handle all the settings, kb id, etc for you without requiring appsettings updates for each KB you add (as it also does for LUIS). 

If you want to use the QnA Maker Action, rather than creating a dialog for your KB, the you need to provide the settings manually in appsettings today.
