### ISSUE TITLE
[NewTemplateRequest]: Bot for AzureDevOps

### ISSUE THREAD

**Issue by irwinwilliams** [microsoft/botframework-components#1328]
Hi there, 
It would be groovy if you could use a bot template that interacted with work items in Azure DevOps. 
My friend and I are going to work on such a bot and going to attempt to do it, using bot framework composer.

**Comment by tracyboehrer** [comment]
@irwinwilliams Not exactly sure how to do this in a generic way.  Would love to see what you come up with.  We have played with bots that do something similar with GitHub.  While you might be able to use Http calls from Composer, it might be easier with a custom component so that you'd have access to using C#.  The next logical step is allowing proactive (push) notifications from DevOps.  Reminders, new PR's, etc...

This isn't something we'll plan on adding.  But convince us differently.  ;-)
