### ISSUE TITLE
CQA

### ISSUE THREAD

**Issue by davidcg96** [microsoft/botframework-components#1498]
I need a template for use CQA with Composer because QnA will deprecated

**Comment by ramfattah** [comment]
Hi @davidcg96, 

There is [CustomQuestionAnswering](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/CustomQuestionAnswering) recognizer package that helps you add a custom recognizer to an empty bot built with Bot Framework Composer in order to use [Azure Custom Question Answering](https://azure.microsoft.com/en-us/products/cognitive-services/question-answering/) in place of the now deprecated QnA Maker.
