### ISSUE TITLE
[NewTemplateRequest]

### ISSUE THREAD

**Issue by anug777** [microsoft/botframework-components#1502]
question answering  cognitive service in Bot Framework Composer

**Comment by ramfattah** [comment]
Hi @anug777,

There is [CustomQuestionAnswering](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/CustomQuestionAnswering) recognizer package that helps you add a custom recognizer to an empty bot built with Bot Framework Composer in order to use [Azure Custom Question Answering](https://azure.microsoft.com/en-us/products/cognitive-services/question-answering/) in place of the now deprecated QnA Maker.
