### ISSUE TITLE
Support inviting attendees by email address

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-components#376]
When I book a meeting using MS account and invite a user like LidiaH@M365xxxx.OnMicrosoft.com, this will fail.
![image](https://user-images.githubusercontent.com/44257569/98762721-4117f600-2413-11eb-84f0-7a5ae509dac7.png)

**Comment by Quirinevwm** [comment]
If it's not possible to include outside of the org, let's include:
**I could not include this attendee, since they are outside of your organization. This will be possible in a later release!

The attendee seems to be outside of your organization. For now please include attendees in your organization. Inclusion will be possible in a later release!**

**Comment by lauren-mills** [comment]
Just to summarize the issue here, you can add people outside of the org, you just can't add people who are not also in your contacts. So we need to be able to support adding an email directly to the attendee list without looking it up in the Contacts or People APIs

**Comment by Quirinevwm** [comment]
That makes sense, let's look at how that logic works in a later stage, can we then introduce the proposed transcript in this way:
- I could not include this attendee, since they are not in your contact list. This will be possible in a later release!
- The attendee does not appear in your email contacts. Additions will be possible in a later release!

**Comment by thomas-chung** [comment]
@Quirinevwm @lauren-mills It is possible to include attendees from outside the organization/AAD tenant. However, as you may know certain functionalities like "find free time" would likely not work given the caller's AAD auth token does not work across tenants.

Even though the case isn't that edge. I think the graph API itself just doesn't quite support that scenario yet so we cannot easily do that either. I don't know if we should mention something will be in later release given there isn't a backlog/date corresponding to when that feature will be available and there isn't even a design that is thought to be possible.

**Comment by lauren-mills** [comment]
Right, I think if an external person is invited, we just skip the find meeting times api, or allow it to follow its default response of "I couldn't find a meeting time for all attendees. When would you like to schedule it?"

The issue right now, is that we are not handling emails directly. If we get an email like above, we pass it into the get contacts api, when instead we should just accept it and add it as an attendee. I have a fix for this in the create flow refactoring.

**Comment by Quirinevwm** [comment]
Nice indeed so for design follow-up on content too:
(i) not in contact list: 
" I could not include this attendee, since they are not in your contact list/ the attendee does not appear in your email contacts." - follow up with **want to add a contact?** (separate component even possibly?)

(ii) in contact list, but no insight for find time (outside AAD).
"For this (some) contact(s) I cannot browse through their availability. What time did you have in mind?"
