### ISSUE TITLE
Calendar skill chokes CPU/Memory

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-components#559]
Using latest calendar skill as integrated into Enterprise assistant (private build).
I noticed my computer chokes every ~5 minutes. I traced it to the Calendar hogging my system.

Note that the bot was running in the background, not doing anything.

We need to watch for that.

![image](https://user-images.githubusercontent.com/8867670/107704387-00c64f00-6c72-11eb-9a12-be797856cca3.png)

**Comment by thomas-chung** [comment]
Hey @scheyal we have taken a look into the memory dump from the calendar skill project. If we break down the memory allocation by GC gen we noticed the highest usage is in Gen 2:

With !dumpgen {Gen} -stats
----------------------------------------
Total GEN 0 size: 76,137,160 bytes
Total GEN 1 size: 40,596,984 bytes
Total GEN 2 size: 115,353,232 bytes

This indicates a lot of things are being held in memory for a long time (possibly due to caching). The top usage in GEN2 is:

     175,904     10,801,824   System.String
     428,633     13,716,256   Antlr4.Runtime.Tree.TerminalNodeImpl
     428,633     27,432,512   Antlr4.Runtime.CommonToken

System.String itself isn't surprising given it's one of the most commonly used types in many application. However, the appearance of Antlr4.* indicates that it has something to do with our LG templates.

If we do a !gcroot on some of these objects, it traces to the ResourceExplorer which to me is clear indication that that most likely our majority of memory consumption is from parsing the LG template (see example below):

            ->  0000020AFD89DCE0 Microsoft.Bot.Builder.Dialogs.Declarative.Resources.ResourceExplorer
            ->  0000020BFDD67168 System.EventHandler`1[[System.Collections.Generic.IEnumerable`1[[Microsoft.Bot.Builder.Dialogs.Declarative.Resources.Resource, Microsoft.Bot.Builder.Dialogs.Declarative]], System.Private.CoreLib]]
            ->  0000020CFDCF1540 Microsoft.Bot.Builder.Dialogs.Adaptive.Generators.LanguageGeneratorManager
            ->  0000020CFDCF15E0 System.Collections.Concurrent.ConcurrentDictionary`2[[System.String, System.Private.CoreLib],[Microsoft.Bot.Builder.Dialogs.Adaptive.LanguageGenerator, Microsoft.Bot.Builder.Dialogs.Adaptive]]
            ->  0000020C7DF066D8 System.Collections.Concurrent.ConcurrentDictionary`2+Tables[[System.String, System.Private.CoreLib],[Microsoft.Bot.Builder.Dialogs.Adaptive.LanguageGenerator, Microsoft.Bot.Builder.Dialogs.Adaptive]]
            ->  0000020C7DF06260 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.String, System.Private.CoreLib],[Microsoft.Bot.Builder.Dialogs.Adaptive.LanguageGenerator, Microsoft.Bot.Builder.Dialogs.Adaptive]][]
            ->  0000020DBDD71DC8 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.String, System.Private.CoreLib],[Microsoft.Bot.Builder.Dialogs.Adaptive.LanguageGenerator, Microsoft.Bot.Builder.Dialogs.Adaptive]]
            ->  0000020C7DF06700 Microsoft.Bot.Builder.Dialogs.Adaptive.Generators.TemplateEngineLanguageGenerator
            ->  0000020C7DF08D78 Microsoft.Bot.Builder.LanguageGeneration.Templates
            ->  0000020DBDD6AD48 System.Collections.Generic.List`1[[Microsoft.Bot.Builder.LanguageGeneration.Templates, Microsoft.Bot.Builder.LanguageGeneration]]
            ->  0000020DBDD6AD68 Microsoft.Bot.Builder.LanguageGeneration.Templates[]
            ->  0000020AFDBF9F88 Microsoft.Bot.Builder.LanguageGeneration.Templates
            ->  0000020DFDF4ABF8 Microsoft.Bot.Builder.LanguageGeneration.Template[]
            ->  0000020DFDEF2840 Microsoft.Bot.Builder.LanguageGeneration.Template
            ->  0000020DFDEF3098 LGTemplateParser+NormalBodyContext
            ->  0000020DFDEF3118 System.Collections.Generic.List`1[[Antlr4.Runtime.Tree.IParseTree, Antlr4.Runtime.Standard]]
            ->  0000020DFDEF3138 Antlr4.Runtime.Tree.IParseTree[]
            ->  0000020DFDEF30D8 LGTemplateParser+NormalTemplateBodyContext
            ->  0000020DFDEF31B0 System.Collections.Generic.List`1[[Antlr4.Runtime.Tree.IParseTree, Antlr4.Runtime.Standard]]
            ->  0000020DFDEF31D0 Antlr4.Runtime.Tree.IParseTree[]
            ->  0000020DFDEF3170 LGTemplateParser+TemplateStringContext
            ->  0000020DFDEF3248 System.Collections.Generic.List`1[[Antlr4.Runtime.Tree.IParseTree, Antlr4.Runtime.Standard]]
            ->  0000020DFDEF3268 Antlr4.Runtime.Tree.IParseTree[]
            ->  0000020DFDEF3208 LGTemplateParser+NormalTemplateStringContext
            ->  0000020DFDEF32C0 System.Collections.Generic.List`1[[Antlr4.Runtime.Tree.IParseTree, Antlr4.Runtime.Standard]]
            ->  0000020DFDEFF378 Antlr4.Runtime.Tree.IParseTree[]
            ->  0000020DFDEF3BC0 Antlr4.Runtime.Tree.TerminalNodeImpl
            ->  0000020DFDEF3B20 Antlr4.Runtime.CommonToken

It is fair to ask whether it is necessarily that big. This is where I am still thinking through the issue. After all, Calendar skill does have a lot of LG templates. However, we might need to actually benchmark memory usage vs LG template counts to determine whether we have any tangible issue, and whether or not there could be any optimization to drive down the memory usage.

For now I will close the issue. Please let us know if you feel otherwise. Thanks!
