### ISSUE TITLE
Chore: Cleanup /skills directory

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#873]
The skills folder needs to be cleaned up, I think the below makes sense. However, we seem to be using the Who/Calendar solutions in the skills folder as the working solutions, then copy/pasting to the /generators folder? If that is the case we'll need to come up with a consistent pattern that we use for all of these (ideally w/o copy/paste of files).

1. Rename to "legacy_VA_Skills" or similar
2. Remove declarative and everything inside, People/Calendar should reside inside the /generator folder
3. Drop the extraneous "csharp" folder

**Comment by lauren-mills** [comment]
We need to have a working version of the skills outside of the generators to run the tests against on PRs to make sure everything works as expected. We can't do that from the generator folder without the runtime

**Comment by peterinnesmsft** [comment]
@clearab +1 to Lauren's point - right now, we simply can't remove this because this is the process for developing skills to be turned into components/generators. I think it is a clunky process that can be improved, and so to me that is actually the thing we should be driving towards.

The csharp directory also should not be considered extraneous - this is the work that was accomplished by the Virtual Assistant team prior to reshuffling. We need to have a direct conversation with Scott to determine what is happening with the previously implemented VA and Skills work. Until that point, these skills should not be dropped.

**Comment by clearab** [comment]
Oh, I didn't mean we should drop the skills in there, just drop the csharp folder from the hierarchy. My current feedback is that having a folder named "skills" that contains things that are actually generators/templates (or maybe just bots), but definitely aren't specifically skills could be confusing. If possible, I'd like to see us not be categorizing People or Calendar as skills in the folder structure.
