### ISSUE TITLE
R13 Bugbash: Creation using Enterprise assistant template took too long

### ISSUE THREAD

**Issue by elaine-chang** [microsoft/botframework-components#951]
## Version

![image](https://user-images.githubusercontent.com/25210203/115445297-86aecb00-a1ca-11eb-989f-3ed582dccc71.png)

## OS
- [x] Windows

## To Reproduce

1. Go to Composer Home
2. Click on 'New'
3. Scroll down to 'Enterprise assistant template'

## Expected behavior

This creation process of Enterprise assistant template should only take a minute or two. 

## Screenshots

![image](https://user-images.githubusercontent.com/25210203/115445524-d2fa0b00-a1ca-11eb-9e51-4cbcd6d84449.png)
![image](https://user-images.githubusercontent.com/25210203/115445596-e86f3500-a1ca-11eb-8021-7bbec3a406fa.png)

**Comment by peterinnesmsft** [comment]
We have had numerous reports around the increased length of time it takes to create a bot in the new Composer flow. @pavolum and I are looking into optimizations that can be made.

**Comment by elaine-chang** [comment]
I re-tested again today creating a new Enterprise assistant from scratch and the time duration has reduced to about 5 minutes now (from 11 minutes 2 days ago). Good to see some improvement. What's the target for the expected time from the beginning to everything loaded with Next Steps shown?  (@lauren-mills @thomas-chung FYI)

**Comment by pavolum** [comment]
@elaine-chang one thing to be aware of is first time to creation is going to be longer then subsequent times as the user installs the yeoman template the first time which adds around 45 seconds to creation time. 11 minutes is much larger then I usually see, let me know if you see that kind of duration time again.

**Comment by peterinnesmsft** [comment]
Hi @elaine-chang! Just wanted to follow up on this some more so we can get aligned on expectations.

There are a number of performance-related issues that are actively being investigated in the new creation flow that impact all bots. As @pavolum mentioned above, there is an additional one-time latency due to having to perform a remote fetch of the template.

There is a known performance issue performing dialog merge which we have an incoming performance fix which should hopefully land in the Composer nightly build next Thursday - this requires publishing a new version of our CLI package, which is targeted for Wednesday 4/28.

As @pavolum says, 11 minutes is a much larger number than the ~45s-1 min period that has typically been reported. It would be good to check in and see if you are seeing this still, or if it has reduced at all. Meanwhile, I can check in with @lauren-mills and @thomas-chung to see if there are any notable things that might add to the overall latency.

**Comment by elaine-chang** [comment]
Just tried this again with today's nightly (5106247). It took about 3.5 minutes with the longest step for merging packages (~1.5-2 minutes).
